name: Ask question
description: Ask react-big-schedule related question
labels: [question]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've looked through the [README](https://github.com/react-scheduler/react-big-schedule#readme)
          required: true
        - label: I've verified that  I am running react-big-schedule latest version.
          required: true
        - label: I've searched the existing issues and discussions for a similar question
        - label: I've provided relevant code snippets or error messages
        - label: I've included steps to reproduce the issue
        - label: I've checked the browser console for any errors
        - label: I've tested the issue with the latest version of react-big-schedule
  - type: textarea
    id: question
    attributes:
      label: Please make sure the question is worded well enough to be understood
      placeholder: Provide any additional information and as much context and examples as possible
    validations:
      required: true
