name: Bug report
description: Report a bug
labels: [triage, bug]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: "I've verified that I'm running react-big-schedule latest version."
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Link/Code
      placeholder: |
        Please add an example code or a reproduction link that can be used to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: howtoreproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: operating_system
    attributes:
      label: Operating System
      placeholder: Enter your operating system
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Enter your browser
    validations:
      required: true
  - type: input
    id: react_version
    attributes:
      label: React version
      placeholder: Enter your React version
    validations:
      required: true
  - type: input
    id: schedule_version
    attributes:
      label: react-big-schedule version
      placeholder: Enter your react-big-schedule version
    validations:
      required: true
  - type: textarea
    id: additionalinfo
    attributes:
      label: Additional Information
      placeholder: Add any additional information about the bug here.
